version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: "***.dkr.ecr.us-east-1.amazonaws.com/my-web-app:backend-latest"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydb
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
