services:
  backend:
    build:
      context: app/
    image: "047719655302.dkr.ecr.us-east-1.amazonaws.com/my-web-app:postgres-14"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydb
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
